live_config_reload = true

[colors]
  draw_bold_text_with_bright_colors = false

  [colors.bright]
    black = '#32302f'
    blue = '#7daea3'
    cyan = '#89b482'
    green = '#a9b665'
    magenta = '#d3869b'
    red = '#ea6962'
    white = '#d4be98'
    yellow = '#d8a657'

  [colors.cursor]
    cursor = '0xe9e9f4'
    text = '0x282936'

  [colors.normal]
    black = '#32302f'
    blue = '#7daea3'
    cyan = '#89b482'
    green = '#a9b665'
    magenta = '#d3869b'
    red = '#ea6962'
    white = '#d4be98'
    yellow = '#d8a657'

  [colors.primary]
    background = '#1d2021'
    foreground = '#d4be98'

[font]
  size = 15.0

  [font.normal]
    family = 'FiraCode Nerd Font Mono'
    style = 'Retina'

[keyboard]
[[keyboard.bindings]]
    chars = "\u001Bb"
    key = 'Left'
    mods = 'Alt'

[[keyboard.bindings]]
    chars = "\u001Bf"
    key = 'Right'
    mods = 'Alt'

[[keyboard.bindings]]
    chars = '€'
    key = 'Key2'
    mods = 'Alt'

[[keyboard.bindings]]
    chars = '#'
    key = 'Key3'
    mods = 'Alt'

[[keyboard.bindings]]
    key = 'N'
    mods = 'Command'

    [keyboard.bindings.command]
      program = '/usr/local/bin/alacritty_new_window_same_dir.sh'

[selection]
  save_to_clipboard = true

[window]
  option_as_alt = 'Both'
