format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$conda\
$line_break\
$status\
$shell\
$character"""
# $docker_context\

add_newline = false

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
ahead      = "⇡${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
behind     = "⇣${count}"
conflicted = "=${count}"
untracked  = "?${count}"
stashed    = "\\$${count}"
modified   = "!${count}"
staged     = "+${count}"
renamed    = "»${count}"
deleted    = "✘${count}"

[java]
format         = "[${symbol}(${version} )]($style)"
version_format = "$major.$minor"
symbol         = " "
style          = "yellow dimmed"

[conda]
ignore_base = false
format      = "[$symbol$environment]($style) "
