# See https://wiki.hyprland.org/Configuring/Monitors/

monitorv2 {
  output = DP-1
  mode = 3840x2160@120
  position = 0x0
  scale = 1
  vrr = 3 # 0: off, 1: on, 2: fullscreen only, 3: fullscreen with video or game content type
  bitdepth = 8
}
monitorv2 {
  output = HDMI-A-1
  disabled = true
}
