# See https://wiki.hyprland.org/Configuring/Monitors/

# 4K x1.875, multi
#monitor=HDMI-A-1, 3840x2160@60, 0x0, 1.875, bitdepth, 8
#monitor=HDMI-A-2, 3840x2160@60, ???, 1.875, transform, 1, bitdepth, 8

# 4k x1.5, multi
monitorv2 {
  output = HDMI-A-1
  mode = 3840x2160@60
  position = 0x0 # impacted by scale!
  scale = 1.5
  vrr = 3 # 0: off, 1: on, 2: fullscreen only, 3: fullscreen with video or game content type
  bitdepth = 8
}
monitorv2 {
  output = HDMI-A-2
  mode = 3840x2160@60
  position = -1440x-560 # impacted by scale!
  scale = 1.5
  vrr = 0 # 0: off, 1: on, 2: fullscreen only, 3: fullscreen with video or game content type
  transform = 1 # 90 degrees, no flip
  bitdepth = 8
}
