general {
    # avoid starting multiple hyprlock instances
    lock_cmd = pidof hyprlock || hyprlock
    # lock before suspend
    before_sleep_cmd = loginctl lock-session
    # to avoid having to press a key twice to turn on the display
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms { action = "enable" }'
}

listener {
    timeout = 600 # 10min
    on-timeout = loginctl lock-session
}
